run:
  name: Run reg-suit
  needs: prepare
  runs-on: ubuntu-latest
  steps:
  - name: checkout
    uses: actions/checkout@v3
    with:
      fetch-depth: 0

  - name: workaround for detached HEAD
    if: ${{ github.event_name == 'pull_request' }}
    run: |
      git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull

  - name: restore yarn cache
    uses: actions/cache@v2
    with:
      path: .yarn/cache/
      key: yarn-${{ hashFiles('**/yarn.lock') }}-v1

  - name: yarn install
    run: yarn install --immutable

  - name: load reg-suit expecteds
    uses: actions/download-artifact@v2
    with:
      name: reg-expected
      path: .reg/

  - name: screenshots
    run: yarn ci:screenshot

  - name: run reg-suit
    run: yarn ci:reg-suit

  - name: upload reg-suit
    uses: actions/upload-artifact@v2
    with:
      name: visual regression test result
      path: .reg/