jobs:
  prepare:
    name: Prepare main branch screenshots
    runs-on: ubuntu-latest
    steps:
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: check commit hash
        id: commithash
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

      - name: restore yarn cache
        uses: actions/cache@v2
        with:
          path: .yarn/cache/
          key: reg-yarn-${{ hashFiles('**/yarn.lock') }}-v1

      - name: restore reg-suit.yml screenshots
        uses: actions/cache@v2
        with:
          path: .reg/
          key: reg-${{ steps.commithash.outputs.hash }}-v7

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".reg/"

      - name: yanr install main branch
        if: steps.check_files.outputs.files_exists == 'false'
        run: yarn install --immutable

      - name: screenshots main branch
        if: steps.check_files.outputs.files_exists == 'false'
        run: yarn ci:screenshot

      - name: run reg-suit.yml main branch
        if: steps.check_files.outputs.files_exists == 'false'
        run: yarn ci:reg-suit.yml

      - name: set reg-suit.yml expected
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          rm -rf .reg/expected/
          mv -f .reg/actual/ .reg/expected/
          mkdir .reg/actual/
          ls -l .reg/
      - name: upload .reg/
        uses: actions/upload-artifact@v2
        with:
          name: reg-expected
          path: .reg/
